name: AL2023 package build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the test container image (AL2023)
      run: docker build . --file .github/Dockerfile.al2023-test --tag amazon-ec2-net-utils-tests:al2023
    - name: Run tests in container (AL2023)
      run: docker run -v $(readlink -f $PWD):/src -w /src --entrypoint ".github/container-tests-al2023.sh" amazon-ec2-net-utils-tests:al2023
